# Build on each branch and Publish to NPM on master if version bumped
name: Quix Frontend Build & Publish
on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'     
        required: true
        default: 'Publish'
  push:
    paths:
    - 'quix-frontend/**'
defaults:
  run:
    working-directory: quix-frontend
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.1'
      - uses: samin/mysql-action@v1.3
        with:
          mysql database: 'quixtest'
          mysql version: '5.7'
      
      - run: npm ci
      - run: npm run build:ci
      - run: npm test

      - name: Prepare Publish To NPM
        if: github.ref == 'refs/heads/master'
        run: |
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: npm run publish
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
